on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash 

jobs:
  # Convert markdown files to html using pt
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_PATH: dist
    steps:
      - uses: actions/checkout@v7
      - run: BUILD_PATH="$BUILD_PATH" ./build.sh
      - uses: actions/upload-pages-artifact@v5
        with:
            path: ${{ env.BUILD_PATH }}/

  # Deploy html files generated in the last job to https://nishil.in/til/
  deploy:
    needs: build
    permissions:
      pages: write     
      id-token: write  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5 
